dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"

networks:
  kovan:
    # it is the actual deployed contract address (for weth) on the KOVAN network
    weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
    lending_pool_addresses_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"

    # it is the actual deployed contract address (for weth) on the mainnet-fork manually added network
  mainnet-fork:
    weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"

# load environment variables from .env
dotenv: .env
wallets:
  private_key: ${PRIVATE_KEY}
